[09:29:55] 📦 Processed dependencies!

cat: /mount/admin/install_path: No such file or directory




2025-08-30 09:30:02.597 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec

    exec(code, module.__dict__)  # noqa: S102

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/automatic-job-apply-agent/job_app.py", line 2, in <module>

    import PyPDF2

ModuleNotFoundError: No module named 'PyPDF2'

[09:30:32] 🐙 Pulling code changes from Github...

[09:30:33] 📦 Processing dependencies...

[09:30:33] 📦 Processed dependencies!

[09:30:34] 🔄 Updated app!

[09:32:02] 🐙 Pulling code changes from Github...

[09:32:03] 📦 Processing dependencies...

[09:32:03] 📦 Processed dependencies!

[09:32:04] 🔄 Updated app!

[09:33:02] 🐙 Pulling code changes from Github...

[09:33:03] 📦 Processing dependencies...

[09:33:03] 📦 Processed dependencies!

[09:33:04] 🔄 Updated app!

[09:41:20] 🐙 Pulling code changes from Github...

[09:41:21] 📦 Processing dependencies...

[09:41:21] 📦 Processed dependencies!

2025-08-30 09:41:21.467 Uncaught app execution

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling

    result = func()

  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec

    exec(code, module.__dict__)  # noqa: S102

    ~~~~^^^^^^^^^^^^^^^^^^^^^^^

  File "/mount/src/automatic-job-apply-agent/job_app.py", line 13, in <module>

    import PyPDF2  # required (not optional)

    ^^^^^^^^^^^^^

ModuleNotFoundError: No module named 'PyPDF2'

[09:41:22] 🔄 Updated app!
